export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS"
export const AUTH_SIGNIN_INIT = "AUTH_SIGNIN_INIT"

export const AUTH_SIGNUP_INIT = "AUTH_SIGNUP_INIT"

export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

